### ISSUE TITLE
Add OpenGraph data for pages

### ISSUE THREAD

**Issue by lectrician1** [maproulette/maproulette3#2248] opened 2024-01-17 22:31 UTC
**Is your feature request related to a problem? Please describe.**
I would like previews to show when I post a link to a maproulette challenge on social media. They currently don't:
![image](https://github.com/maproulette/maproulette3/assets/22477298/e85ca256-cfea-4261-98dd-fbdbce5e2963)

**Describe the solution you'd like**
Previews to show through [OpenGraph](https://ogp.me/) data

**Describe alternatives you've considered**
None applicable.

**Additional context**

**Comment by amandasaurus** [comment] 2024-01-18 09:47
You can use something like https://www.opengraph.xyz/ to generate the HTML tags that you need & just copy paste in,

**Comment by danieldegroot2** [comment] 2024-01-19 14:59
Duplicate of #1755

**Closed** 2024-01-25 21:18 UTC
Labels: enhancement
