### ISSUE TITLE
Tasks partially loaded

### ISSUE THREAD

**Issue by rmikke** [maproulette/maproulette3#264] opened 2018-03-30 18:16 UTC
I have created a challenge 2962 based on Overpass query http://overpass-turbo.eu/s/xtW . The query itself returns quite a lot of results. But MapRoulette changes status from "building tasks" to "partially loaded" and stays so for all day. I've tried to rebuild it yesterday once and today. Why is that so?

**Comment by mvexel** [comment] 2018-03-30 18:24
That's strange. The challenge does seem to 'work' already, http://maproulette.org/mr3/challenge/2962 

But I can confirm that the status seems to be 'stuck' at 'Partially loaded'. 

We'll have to look into that one. Thanks for reporting!

**Comment by rmikke** [comment] 2018-03-30 18:31
Well, it also does not show on the challenge list although I've marked it as "visible".

**Comment by mgcuthbert** [comment] 2018-03-30 19:25
The partially loaded state, is actually a form of a complete state. Basically the during the creation of tasks from the overpass query some of the tasks failed to be created due to some error. The new MR3 UI needs to handle this state a little differently and show the tasks.

**Comment by nrotstan** [comment] 2018-03-31 00:20
Thanks for the report! The fix for this will be included in the beta.4 release.

**Closed** 2018-04-03 04:53 UTC
Labels: bug, fixed in develop
