### ISSUE TITLE
Feature request: allow having overlay layers on by default in challenge

### ISSUE THREAD

**Issue by cbeddow** [maproulette/maproulette3#1197] opened 2020-04-01 11:34 UTC
Right now, the user can can toggle on extra layers like OSM Data, Mapillary, and OpenStreetCam.

It would be very helpful when setting up the challenge to make it so these layers are automatically available. In this case the user could have satellite basemap, OSM data, overlay, and if they are looking for tasks where they can add a shop name for example, they would be able to know immediately if Mapillary/OSC imagery is available to help them, or if it's too hard/can't see because of no street imagery.

I would suggest a simple dropdown with check boxes in the same challenge setup area where the basemap can be chosen.

**Comment by danieldegroot2** [comment] 2022-10-04 20:29
@cbeddow Duplicate of #844 (unless you mean opening with certain layers in an editor)
If this is a duplicate, you should change the title of the original issue to reflect that it is about any overlay.

**Comment by mvexel** [comment] 2023-02-08 16:43
yep closing as duplicate, thanks @danieldegroot2

**Closed by mvexel** 2023-02-08 16:43 UTC
