### ISSUE TITLE
Rapid fails to appear

### ISSUE THREAD

**Issue by davidpnewton** [maproulette/maproulette3#2469] opened 2024-10-18 14:08 UTC
**Describe the bug**
Upon attempting to complete a challenge task using Rapid an error message is produced and no instance of Rapid appears.

**Expected behavior**
Rapid appearing with the element of the challenge selected and ready for editing.

**To Reproduce**
Go into a challenge, browse for the tasks in the challenge and then try to start a task.

**Screenshots**
![image](https://github.com/user-attachments/assets/19517dbe-0270-41c9-b293-63786d6576b6)

 - Windows 11 23H2
 - Chrome 129.0.6668

**Additional context**
There was a commit a couple of days ago taking the version of Rapid used from 2.3.2 to 2.4. The problem started around then.

**Comment by ChicoXXX** [comment] 2024-10-18 15:11
Same bug in : 

- Debian 12
- Brave Versión 1.71.114

**Comment by CollinBeczak** [comment] 2024-10-18 15:23
Hmm.... it's broken again. I'll keep looking into the cause

**Comment by CollinBeczak** [comment] 2024-10-18 15:42
This appears to be a race condition on MapRoulettes side, where maproulette is trying to setup the iframe before it is loaded. For now if you want to use the iframe, you will need to toggle off and back on the rapid editor. I will get to work on fixing that race condition.

**Comment by davidpnewton** [comment] 2024-10-18 22:36
You know there is a certain amusing irony for Rapid being the subject of a race condition.

**Comment by CollinBeczak** [comment] 2024-10-22 18:16
this should be fixed now that this has been merged and deployed: https://github.com/maproulette/maproulette3/pull/2472

**Closed by CollinBeczak** 2024-10-22 18:16 UTC
Labels: bug

**Comment by davidpnewton** [comment] 2024-10-22 22:28
Can confirm it appears to be fixed for me.
