### ISSUE TITLE
Not able to open challenges or log in on MapRoulette

### ISSUE THREAD

**Issue by Jorieke** [maproulette/maproulette3#2272] opened 2024-02-19 09:47 UTC
Hello 

MapRoulette does not seem to work…  The main page opens, but it is not possible to search for a challenge or to log in. 

See screenshot: 
![image](https://github.com/maproulette/maproulette3/assets/6013645/c5a06e1a-91a4-4ccf-b3e9-1d970910c83d)

**Comment by ljdelight** [comment] 2024-02-23 08:12
@Jorieke, thank you for reporting the issue! MapRoulette recovered after some time, and we've seen similar stability issues lately and have been looking closely to identify the cause and preconditions of the failure. One PR is in flight and others on the way.

**Comment by mvexel** [comment] 2024-02-28 00:09
As this was an isolated instance and we have a bigger effort going on to mitigate the recent outages, I'll close this particular ticket.

**Closed by mvexel** 2024-02-28 00:09 UTC
Labels: bug
