### ISSUE TITLE
When looking at one of your own challenges, add a 'manage' button

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette3#175] opened 2018-03-13 17:22 UTC
If looking at one of your 'own' challenges in the list, add a button to go to the manage page for that challenge.

**Comment by nrotstan** [comment] 2018-03-15 13:59
Is this a duplicate of #87, or is this intended to represent an additional spot in which you'd like to see a manage control?

**Comment by mvexel** [comment] 2018-03-15 16:22
It isn't an exact duplicate, but I think having it in challenge browse mode makes more sense than having it when looking at a task. Closing #87

**Closed** 2018-04-03 04:56 UTC
Labels: UX / UI, enhancement, fixed in develop
